<?php
include "db_conn.php";

echo "<h2>Testing Report Interfaces</h2>\n";

// Test reports query
echo "<h3>Existing Reports Query Test</h3>\n";
$sql = "SELECT r.*, u.name as generated_by_name 
        FROM reports r 
        JOIN users u ON r.generated_by = u.id 
        ORDER BY r.created_at DESC
        LIMIT 5";

$result = mysqli_query($conn, $sql);

if ($result) {
    echo "<p>Reports query executed successfully.</p>\n";
    echo "<p>Found " . mysqli_num_rows($result) . " reports.</p>\n";
    
    if (mysqli_num_rows($result) > 0) {
        echo "<table border='1' cellpadding='5'>\n";
        echo "<tr><th>Title</th><th>Type</th><th>Format</th><th>Generated By</th><th>Date</th></tr>\n";
        
        while ($report = mysqli_fetch_assoc($result)) {
            echo "<tr>";
            echo "<td>" . htmlspecialchars($report['title']) . "</td>";
            echo "<td>" . htmlspecialchars($report['report_type']) . "</td>";
            echo "<td>" . htmlspecialchars($report['format']) . "</td>";
            echo "<td>" . htmlspecialchars($report['generated_by_name']) . "</td>";
            echo "<td>" . htmlspecialchars($report['created_at']) . "</td>";
            echo "</tr>\n";
        }
        
        echo "</table>\n";
    }
} else {
    echo "<p>Error executing reports query: " . mysqli_error($conn) . "</p>\n";
}

echo "<h3>Interface Access</h3>\n";
echo "<p>To access the report interfaces:</p>\n";
echo "<ul>\n";
echo "<li>Log in as admin (username: elias, password: 1234)</li>\n";
echo "<li>Navigate to 'Reports' > 'View Reports' to see existing reports</li>\n";
echo "<li>Navigate to 'Reports' > 'Export Reports' to generate new reports</li>\n";
echo "<li>Navigate to 'Reports' > 'Generate Reports' to create reports with custom options</li>\n";
echo "</ul>\n";

echo "<h3>Report Types Available</h3>\n";
echo "<ul>\n";
echo "<li>Student Attendance Reports</li>\n";
echo "<li>Tutor-Student Matching Reports</li>\n";
echo "<li>Staff Attendance Reports</li>\n";
echo "</ul>\n";

echo "<h3>Export Formats Supported</h3>\n";
echo "<ul>\n";
echo "<li>Excel (.xls)</li>\n";
echo "<li>PDF (.pdf)</li>\n";
echo "<li>CSV (.csv)</li>\n";
echo "</ul>\n";
?>