<?php
$success_message = '';
$error_message = '';
$generated_student_id = '';

// Get the next student ID that will be generated
$year_prefix = date('Y');
$next_id_sql = "SELECT COALESCE(MAX(CAST(SUBSTRING(student_id, 6) AS UNSIGNED)), 0) + 1 as next_num 
                FROM students 
                WHERE student_id LIKE CONCAT('$year_prefix', '-%')";
$next_id_result = mysqli_query($conn, $next_id_sql);
$next_id_row = mysqli_fetch_assoc($next_id_result);
$next_student_id = $year_prefix . '-' . str_pad($next_id_row['next_num'], 2, '0', STR_PAD_LEFT);

// Handle form submission
if ($_SERVER['REQUEST_METHOD'] == 'POST' && isset($_POST['add_student'])) {
    // student_id will be auto-generated
    $first_name = mysqli_real_escape_string($conn, trim($_POST['first_name']));
    $last_name = mysqli_real_escape_string($conn, trim($_POST['last_name']));
    $email = mysqli_real_escape_string($conn, trim($_POST['email']));
    $phone = mysqli_real_escape_string($conn, trim($_POST['phone']));
    $date_of_birth = mysqli_real_escape_string($conn, $_POST['date_of_birth']);
    $address = mysqli_real_escape_string($conn, trim($_POST['address']));
    $enrollment_date = mysqli_real_escape_string($conn, $_POST['enrollment_date']);
    $status = mysqli_real_escape_string($conn, $_POST['status']);

    if (empty($first_name) || empty($last_name) || empty($enrollment_date)) {
        $error_message = 'Please fill in all required fields.';
    } else {
        // Check if email already exists (if provided)
        if (!empty($email)) {
            $check_sql = "SELECT id FROM students WHERE email = ?";
            $stmt = mysqli_prepare($conn, $check_sql);
            mysqli_stmt_bind_param($stmt, "s", $email);
            mysqli_stmt_execute($stmt);
            $check_result = mysqli_stmt_get_result($stmt);
            
            if (mysqli_num_rows($check_result) > 0) {
                $error_message = 'Email already exists.';
                mysqli_stmt_close($stmt);
            } else {
                mysqli_stmt_close($stmt);
                // Insert new student (student_id will be auto-generated by trigger)
                $insert_sql = "INSERT INTO students (first_name, last_name, email, phone, date_of_birth, address, enrollment_date, status) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
                $stmt = mysqli_prepare($conn, $insert_sql);
                mysqli_stmt_bind_param($stmt, "ssssssss", $first_name, $last_name, $email, $phone, $date_of_birth, $address, $enrollment_date, $status);
                
                if (mysqli_stmt_execute($stmt)) {
                    // Get the generated student_id
                    $last_id = mysqli_insert_id($conn);
                    $get_id_sql = "SELECT student_id FROM students WHERE id = ?";
                    $id_stmt = mysqli_prepare($conn, $get_id_sql);
                    mysqli_stmt_bind_param($id_stmt, "i", $last_id);
                    mysqli_stmt_execute($id_stmt);
                    $id_result = mysqli_stmt_get_result($id_stmt);
                    $id_row = mysqli_fetch_assoc($id_result);
                    $generated_student_id = $id_row['student_id'];
                    mysqli_stmt_close($id_stmt);
                    
                    $success_message = 'Student added successfully!';
                    $_POST = array();
                    
                    // Recalculate next ID
                    $next_id_result = mysqli_query($conn, $next_id_sql);
                    $next_id_row = mysqli_fetch_assoc($next_id_result);
                    $next_student_id = $year_prefix . '-' . str_pad($next_id_row['next_num'], 2, '0', STR_PAD_LEFT);
                } else {
                    $error_message = 'Error adding student: ' . mysqli_error($conn);
                }
                mysqli_stmt_close($stmt);
            }
        } else {
            // No email provided, just insert
            $insert_sql = "INSERT INTO students (first_name, last_name, email, phone, date_of_birth, address, enrollment_date, status) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
            $stmt = mysqli_prepare($conn, $insert_sql);
            mysqli_stmt_bind_param($stmt, "ssssssss", $first_name, $last_name, $email, $phone, $date_of_birth, $address, $enrollment_date, $status);
            
            if (mysqli_stmt_execute($stmt)) {
                // Get the generated student_id
                $last_id = mysqli_insert_id($conn);
                $get_id_sql = "SELECT student_id FROM students WHERE id = ?";
                $id_stmt = mysqli_prepare($conn, $get_id_sql);
                mysqli_stmt_bind_param($id_stmt, "i", $last_id);
                mysqli_stmt_execute($id_stmt);
                $id_result = mysqli_stmt_get_result($id_stmt);
                $id_row = mysqli_fetch_assoc($id_result);
                $generated_student_id = $id_row['student_id'];
                mysqli_stmt_close($id_stmt);
                
                $success_message = 'Student added successfully!';
                $_POST = array();
                
                // Recalculate next ID
                $next_id_result = mysqli_query($conn, $next_id_sql);
                $next_id_row = mysqli_fetch_assoc($next_id_result);
                $next_student_id = $year_prefix . '-' . str_pad($next_id_row['next_num'], 2, '0', STR_PAD_LEFT);
            } else {
                $error_message = 'Error adding student: ' . mysqli_error($conn);
            }
            mysqli_stmt_close($stmt);
        }
    }
}
?>

<style>
    .alert {
        padding: 12px 20px;
        margin-bottom: 20px;
        border-radius: 4px;
        font-weight: 500;
    }
    .alert-success {
        background-color: #d4edda;
        color: #155724;
        border: 1px solid #c3e6cb;
    }
    .alert-danger {
        background-color: #f8d7da;
        color: #721c24;
        border: 1px solid #f5c6cb;
    }
    .card {
        background: #fff;
        border-radius: 8px;
        box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        padding: 30px;
        max-width: 800px;
        margin: 0 auto;
    }
    .card-header {
        margin-bottom: 25px;
        padding-bottom: 15px;
        border-bottom: 2px solid #f0f0f0;
    }
    .card-title {
        font-size: 1.8em;
        font-weight: bold;
        color: #2c3e50;
        margin: 0;
    }
    .form-group {
        margin-bottom: 20px;
    }
    .form-group label {
        display: block;
        margin-bottom: 8px;
        font-weight: 600;
        color: #2c3e50;
    }
    .form-group label .required {
        color: #e74c3c;
    }
    .form-control {
        width: 100%;
        padding: 10px 15px;
        border: 1px solid #ddd;
        border-radius: 4px;
        font-size: 14px;
        transition: border-color 0.3s;
    }
    .form-control:focus {
        outline: none;
        border-color: #3498db;
    }
    .form-row {
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: 20px;
    }
    .btn {
        padding: 12px 30px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        font-size: 14px;
        font-weight: 600;
        text-decoration: none;
        display: inline-block;
        transition: all 0.3s;
        margin-right: 10px;
    }
    .btn-primary {
        background: #3498db;
        color: #fff;
    }
    .btn-primary:hover {
        background: #2980b9;
    }
    .form-actions {
        margin-top: 30px;
        padding-top: 20px;
        border-top: 1px solid #f0f0f0;
    }
    textarea.form-control {
        min-height: 100px;
        resize: vertical;
    }
    @media (max-width: 768px) {
        .form-row {
            grid-template-columns: 1fr;
        }
    }
</style>

<div class="card">
    <div class="card-header">
        <h2 class="card-title"><i class="fas fa-user-graduate"></i> Add New Student</h2>
    </div>

    <?php if ($success_message): ?>
        <div class="alert alert-success">
            <i class="fas fa-check-circle"></i> <?php echo $success_message; ?>
            <?php if ($generated_student_id): ?>
                <br><strong>Generated Student ID: <span style="font-size:1.2em;color:#155724;"><?php echo htmlspecialchars($generated_student_id); ?></span></strong>
            <?php endif; ?>
        </div>
    <?php endif; ?>

    <?php if ($error_message): ?>
        <div class="alert alert-danger">
            <i class="fas fa-exclamation-circle"></i> <?php echo $error_message; ?>
        </div>
    <?php endif; ?>

    <form method="POST" action="">
        <div class="alert" style="background-color: #d1ecf1; color: #0c5460; border: 1px solid #bee5eb;">
            <i class="fas fa-info-circle"></i> <strong>Auto-Generated ID:</strong> The next student will receive ID: <strong style="font-size:1.1em;"><?php echo htmlspecialchars($next_student_id); ?></strong>
        </div>

        <div class="form-group">
            <label for="enrollment_date">Enrollment Date <span class="required">*</span></label>
            <input type="date" class="form-control" id="enrollment_date" name="enrollment_date" 
                   value="<?php echo isset($_POST['enrollment_date']) ? htmlspecialchars($_POST['enrollment_date']) : ''; ?>" required>
        </div>

        <div class="form-row">
            <div class="form-group">
                <label for="first_name">First Name <span class="required">*</span></label>
                <input type="text" class="form-control" id="first_name" name="first_name" 
                       value="<?php echo isset($_POST['first_name']) ? htmlspecialchars($_POST['first_name']) : ''; ?>" required>
            </div>
            <div class="form-group">
                <label for="last_name">Last Name <span class="required">*</span></label>
                <input type="text" class="form-control" id="last_name" name="last_name" 
                       value="<?php echo isset($_POST['last_name']) ? htmlspecialchars($_POST['last_name']) : ''; ?>" required>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" class="form-control" id="email" name="email" 
                       value="<?php echo isset($_POST['email']) ? htmlspecialchars($_POST['email']) : ''; ?>">
            </div>
            <div class="form-group">
                <label for="phone">Phone</label>
                <input type="tel" class="form-control" id="phone" name="phone" 
                       value="<?php echo isset($_POST['phone']) ? htmlspecialchars($_POST['phone']) : ''; ?>">
            </div>
        </div>

        <div class="form-row">
            <div class="form-group">
                <label for="date_of_birth">Date of Birth</label>
                <input type="date" class="form-control" id="date_of_birth" name="date_of_birth" 
                       value="<?php echo isset($_POST['date_of_birth']) ? htmlspecialchars($_POST['date_of_birth']) : ''; ?>">
            </div>
            <div class="form-group">
                <label for="status">Status</label>
                <select class="form-control" id="status" name="status">
                    <option value="Active" <?php echo (isset($_POST['status']) && $_POST['status'] == 'Active') ? 'selected' : ''; ?>>Active</option>
                    <option value="Inactive" <?php echo (isset($_POST['status']) && $_POST['status'] == 'Inactive') ? 'selected' : ''; ?>>Inactive</option>
                    <option value="Graduated" <?php echo (isset($_POST['status']) && $_POST['status'] == 'Graduated') ? 'selected' : ''; ?>>Graduated</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            <label for="address">Address</label>
            <textarea class="form-control" id="address" name="address"><?php echo isset($_POST['address']) ? htmlspecialchars($_POST['address']) : ''; ?></textarea>
        </div>

        <div class="form-actions">
            <button type="submit" name="add_student" class="btn btn-primary">
                <i class="fas fa-save"></i> Add Student
            </button>
        </div>
    </form>
</div>
