<?php
// Get existing reports from database
$sql = "SELECT r.*, u.name as generated_by_name 
        FROM reports r 
        JOIN users u ON r.generated_by = u.id 
        ORDER BY r.created_at DESC";
$result = mysqli_query($conn, $sql);
?>

<div style="background:#fff;padding:30px;border-radius:8px;box-shadow:0 2px 4px rgba(0,0,0,0.1);">
    <h2><i class="fas fa-chart-bar"></i> View Reports</h2>
    <p>Browse and view previously generated reports.</p>
    
    <?php if ($result && mysqli_num_rows($result) > 0): ?>
        <div style="overflow-x:auto;margin-top:20px;">
            <table style="width:100%;border-collapse:collapse;">
                <thead>
                    <tr style="background:#f8f9fa;">
                        <th style="padding:12px;text-align:left;border-bottom:2px solid #dee2e6;">Report Title</th>
                        <th style="padding:12px;text-align:left;border-bottom:2px solid #dee2e6;">Type</th>
                        <th style="padding:12px;text-align:left;border-bottom:2px solid #dee2e6;">Format</th>
                        <th style="padding:12px;text-align:left;border-bottom:2px solid #dee2e6;">Generated By</th>
                        <th style="padding:12px;text-align:left;border-bottom:2px solid #dee2e6;">Date Generated</th>
                        <th style="padding:12px;text-align:left;border-bottom:2px solid #dee2e6;">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php while ($report = mysqli_fetch_assoc($result)): ?>
                        <tr style="border-bottom:1px solid #dee2e6;">
                            <td style="padding:12px;"><?php echo htmlspecialchars($report['title']); ?></td>
                            <td style="padding:12px;">
                                <span style="padding:4px 8px;border-radius:4px;font-size:0.85em;background:#e9ecef;color:#495057;">
                                    <?php 
                                    switch($report['report_type']) {
                                        case 'attendance': echo 'Attendance'; break;
                                        case 'tutor_matching': echo 'Tutor Matching'; break;
                                        case 'staff_attendance': echo 'Staff Attendance'; break;
                                        case 'student_performance': echo 'Student Performance'; break;
                                        default: echo ucfirst(str_replace('_', ' ', $report['report_type']));
                                    }
                                    ?>
                                </span>
                            </td>
                            <td style="padding:12px;">
                                <span style="padding:4px 8px;border-radius:4px;font-size:0.85em;background:#d1ecf1;color:#0c5460;">
                                    <?php echo strtoupper($report['format']); ?>
                                </span>
                            </td>
                            <td style="padding:12px;"><?php echo htmlspecialchars($report['generated_by_name']); ?></td>
                            <td style="padding:12px;"><?php echo date('M j, Y g:i A', strtotime($report['created_at'])); ?></td>
                            <td style="padding:12px;">
                                <a href="?page=generate_reports&generate=1&report_id=<?php echo $report['id']; ?>" 
                                   style="padding:6px 12px;background:#3498db;color:white;text-decoration:none;border-radius:4px;font-size:0.9em;">
                                    <i class="fas fa-eye"></i> View
                                </a>
                            </td>
                        </tr>
                    <?php endwhile; ?>
                </tbody>
            </table>
        </div>
    <?php else: ?>
        <div style="background:#f8d7da;color:#721c24;padding:15px;border-radius:4px;margin-top:20px;">
            <strong>No reports found.</strong> There are no reports generated yet. Go to "Generate Reports" to create new reports.
        </div>
    <?php endif; ?>
    
    <div style="margin-top:30px;padding:20px;background:#f8f9fa;border-radius:8px;">
        <h4><i class="fas fa-info-circle"></i> Report Information</h4>
        <p>Reports are automatically saved after generation. You can view, download, or print any previously generated report from this page.</p>
        <p>To generate new reports, go to <a href="?page=generate_reports" style="color:#3498db;">Generate Reports</a>.</p>
    </div>
</div>